const characters = [
{name:"Buff Shroom",faction:"Fungi", description:"A slow-moving heavy-hitting brute", strength: 7, skill:1, health: 7, rangeMin: 1, rangeMax: 1, attackType: "crushing,poison", weakness: "fire", immunity: "poison", pointValue: 15, x:0, y:96},
{name:"Sandy Slime",faction:"Fungi", description:"Fast-moving cannon fodder", strength: 1, skill:3, health: 1, rangeMin: 1, rangeMax: 1, attackType: "piercing", weakness: "fire", immunity: "poison", pointValue: 5, x:32, y:96},
{name:"Poison Slime",faction:"Fungi", description:"Fast-moving poisonous cannon fodder", strength: 2, skill:3, health: 2, rangeMin: 1, rangeMax: 1, attackType: "poison", weakness: "fire", immunity: "poison", pointValue: 10, x:64, y:96},
{name:"Murder Tree",faction:"Fungi", description:"Waits for unsuspecting victims to get within reach, then strikes mercilessly", strength:10, skill:1, health:14, rangeMin:1,rangeMax:1, attackType:"crushing,piercing,slashing", weakness: "fire", immunity:"poison", pointValue:25, x:96, y:96},
{name:"Fire Shroom",faction:"Fungi", description:"Its superheated body ignites enemies on contact", strength:8, skill:2, health:8, rangeMin: 1, rangeMax: 1, attackType:"crushing,fire", weakness:"crushing", immunity:"fire", pointValue: 20, x:128, y:96},
{name:"Puff Shroom",faction:"Fungi", description:"A fragile, fast-moving balloon filled with poisonous gas", strength:2, skill:3, health:2, rangeMin: 1, rangeMax: 2, attackType:"poison,aoe", weakness:"piercing",immunity:"poison", pointValue: 10, x:160, y:96},
{name:"Mega Centipede",faction:"Bugs", description:"An armored venomous monstrosity that strikes with blinding speed", strength:8, skill:8, health:8, rangeMin: 1, rangeMax: 1, attackType:"piercing,poison", weakness:"crushing",immunity:"poison", pointValue: 25, x:192, y:96},
{name:"Enormous Beetle",faction:"Bugs", description:"A living tank that attacks in sweeping arcs", strength:8, skill:2, health:8, rangeMin: 1, rangeMax: 1, attackType:"crushing,arc", weakness:"fire",immunity:"crushing", pointValue: 20, x:224, y:96},
{name:"Caterpillar",faction:"Bugs", description:"Slow and squishy, it smothers enemies with its bulk", strength:5, skill:1, health:4, rangeMin: 1, rangeMax: 2, attackType:"crushing", weakness:"crushing,fire",immunity:"piercing", pointValue: 10, x:256, y:96},
{name:"Scorpion",faction:"Bugs", description:"Moderate speed and a venomous stinger make this creepy crawlie a solid addition to any army", strength:4, skill:2, health:4, rangeMin: 1, rangeMax: 2, attackType:"piercing,poison", weakness:"fire, crushing",immunity:"poison", pointValue: 10, x:288, y:96},
{name:"Spiny Worm",faction:"Bugs", description:"The only ranged unit for this faction, it launches its venomous spines from afar. It is defenseless in close combat.", strength:3, skill:2, health:3, rangeMin: 2, rangeMax: 4, attackType:"piercing,poison", weakness:"fire,crushing,piercing",immunity:"poison", pointValue: 10, x:320, y:96},
{name:"Spider",faction:"Bugs", description:"Fast, squishy, venomous, the cannon fodder for this faction", strength:1, skill:3, health:1, rangeMin: 1, rangeMax: 1, attackType:"piercing,poison", weakness:"fire,piercing,crushing",immunity:"poison", pointValue: 5, x:352, y:96},
{name:"Peasant Pikeman",faction:"Human", description:"Unskilled, expendable front-line troops", strength:2, skill:1, health:2, rangeMin: 1, rangeMax: 2, attackType:"piercing", weakness:"poison",immunity:"piercing", pointValue: 5, x:0, y:160},
{name:"Magus",faction:"Human", description:"Defenseless at close range, these masters of the arcane arts launch explosive fireballs", strength:5, skill:2, health:5, rangeMin: 2, rangeMax: 5, attackType:"fire,aoe", weakness:"poison,piercing,crushing",immunity:"fire", pointValue: 15, x:32, y:160},
{name:"Archer",faction:"Human", description:"Highly skilled veterans whose abilities fetch a high price. Defenseless at close range.", strength:5, skill:5, health:5, rangeMin: 2, rangeMax: 6, attackType:"piercing", weakness:"poison,piercing,fire",immunity:"crushing", pointValue: 20, x:64, y:160},
{name:"Brute",faction:"Human", description:"Strong, heavily armored warriors that attack in sweeping arcs", strength:12, skill:1, health:12, rangeMin: 1, rangeMax: 2, attackType:"piercing,crushing,arc", weakness:"fire",immunity:"piercing,crushing", pointValue: 25, x:96, y:160},
{name:"Grenadier",faction:"Human", description:"A lightly-armored alchemist with a variety of arcane concoctions", strength:3, skill:2, health:3, rangeMin: 1, rangeMax: 2, attackType:"poison,fire,pheremone,aoe", weakness:"crushing,piercing",immunity:"fire,poison,pheremone", pointValue: 10, x:128, y:160}
];

module.exports = characters;